services:
  # Gitea Git server with issue tracking
  gitea:
    image: gitea/gitea:1.21
    container_name: gitea
    ports:
      - "3030:3000"
      - "2222:22"
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=http://localhost:3030/
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__webhook__ALLOWED_HOST_LIST=*
    networks:
      - agent-network
    restart: unless-stopped

  # MCP Server for Git repository access with Gitea integration
  mcp-git-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: mcp-git-server
    ports:
      - "8089:8089"
    volumes:
      - ./repositories:/workspace/repositories
      - ./mcp-server/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MCP_PORT=8089
      - GIT_CONFIG_GLOBAL_USER_NAME=AI Agent
      - GIT_CONFIG_GLOBAL_USER_EMAIL=agent@example.com
      - GITEA_URL=http://gitea:3000
      - GITEA_TOKEN=${GITEA_TOKEN}
      - GITEA_WEBHOOK_SECRET=${GITEA_WEBHOOK_SECRET}
    networks:
      - agent-network
    depends_on:
      - gitea
    restart: unless-stopped

  # Dev Container Environment
  dev-container:
    build:
      context: ./dev-container
      dockerfile: Dockerfile
    container_name: dev-container
    ports:
      - "3000-3010:3000-3010"  # Range for development servers
      - "8000-8010:8000-8010"  # Additional port range
    volumes:
      - ./repositories:/workspace/repositories
      - ./dev-container/config:/workspace/config
      - dev-container-home:/home/developer
    environment:
      - WORKSPACE_DIR=/workspace/repositories
      - USER=developer
      - UID=1000
      - GID=1000
    networks:
      - agent-network
    depends_on:
      - mcp-git-server
    restart: unless-stopped
    tty: true
    stdin_open: true

  # Agent Orchestrator (handles Claude/OpenAI interactions)
  agent-orchestrator:
    build:
      context: ./agent-orchestrator
      dockerfile: Dockerfile
    container_name: agent-orchestrator
    ports:
      - "9000:9000"
    volumes:
      - ./agent-orchestrator/config:/app/config
      - ./logs:/app/logs
    environment:
      - MCP_SERVER_URL=http://mcp-git-server:8089
      - DEV_CONTAINER_URL=http://dev-container:22
      - LOG_LEVEL=info
    networks:
      - agent-network
    depends_on:
      - mcp-git-server
      - dev-container
    restart: unless-stopped

  # Optional: Web UI for monitoring and control
  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    container_name: agent-web-ui
    ports:
      - "4000:4000"
    environment:
      - AGENT_ORCHESTRATOR_URL=http://agent-orchestrator:9000
      - MCP_SERVER_URL=http://mcp-git-server:8089
    networks:
      - agent-network
    depends_on:
      - agent-orchestrator
    restart: unless-stopped

networks:
  agent-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

volumes:
  dev-container-home:
    driver: local
  gitea-data:
    driver: local
